version: '3.7'

services:
  phantom-x-bot:
    build:
      context: ./docker/node
    volumes:
      - ./:/srv/app:rw,cached
    env_file:
      - .env
    stdin_open: true
    tty: true
    labels:
      - word.enable=true
    networks:
      - phantom_x_network
    restart: always

networks:
  phantom_x_network:
    external: true
    name: bot_phantom_x_network